"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import { usePathname } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


//  i have to comment out the metadata because i make my layout as a clinet side rendering so we can not export in the metadta
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const isNotRoute = pathname.startsWith("/stores") || pathname.startsWith("/admin/all-teams-data/team-noida")
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {!isNotRoute && <Header />}
        {children}
        {!isNotRoute && <Footer />}
      </body>
    </html>
  );
}
