import { Geist, Geist_Mono } from "next/font/google";
import "../../app/globals.css";
import Header from "../Header";
import Footer from "../Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({ children }) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
